# Backend configuration for storing Terraform state in S3
# This allows for team collaboration, state locking, and versioning
#
# To use with different environments, initialize with:
# terraform init -backend-config="key=environments/dev/terraform.tfstate"
# terraform init -backend-config="key=environments/staging/terraform.tfstate"
# terraform init -backend-config="key=environments/prod/terraform.tfstate"
#
# This file was generated by generate-backend.sh script.
# Do not edit this file directly. Instead, modify the script or use backend-config parameters.
#
# Note: The bucket and dynamodb_table names follow the pattern:
# - bucket: "${var.project_name}-terraform-state"
# - dynamodb_table: "${var.project_name}-terraform-locks"
#
# However, variables cannot be used directly in the backend configuration.
# The values here are generated based on the project_name in variables.tf.
# terraform {
#   backend "s3" {
#     bucket         = "invoicedev-terraform-state"
#     key            = "environments/prod/terraform.tfstate"  # Default state file path, override with -backend-config
#     region         = "us-east-1"
#     encrypt        = true
#     dynamodb_table = "invoicedev-terraform-locks"
#   }
# }